#!/bin/bash

trap 'kill $(jobs -p)' EXIT

HTTP_PATH="/omg/wtf" HTTP_USERNAME="test" HTTP_PASSWORD="password" node index.js &

sleep 3 # wait for boot and load


# test userId is in list

code=$(curl \
  --header "Content-Type: text/plain" \
  --user test:password \
  --request POST \
  --data '{"message":"{\"timeRangeStart\":1571245940546,\"timeRangeEnd\":1571246360547,\"userId\":\"6e3a7fe8-c4c9-41dd-8510-0c203b75e09a\",\"appId\":\"com.nike.ntc.brand.ios\",\"sources\":[\"nike.ntc.ios\"],\"metricTypes\":[\"rpe\",\"calories\",\"nikefuel\"],\"activityId\":\"8ed06ba3-d12c-4dc1-a773-cba81a0f0c5c\",\"receivedTime\":1571246402784,\"changeToken\":\"5819147260e25392eecbb1ab10480a1ed3bc600c8a379a88a035fa163d505e44:1571246402784\",\"changeType\":\"update\",\"payloadType\":\"activity\",\"session\":false,\"activityType\":\"training\"}","trace":{"parentId":"-2721724131837535344","spanId":"-8694889937887914020","spanName":"persistAndEnqueueSync","userId":"0353d6f5-f7e9-4830-a803-a1fc370bfa04","traceId":"0c967b6959f4284c","sampleable":false,"traceStartTimeNanos":1017120644185959}}' \
  -o /dev/null \
  -s \
  -w "%{http_code}" \
  localhost:3000/omg/wtf)

expected=201
if [ "$code" != "$expected" ]; then
  echo "Failed! Reponse code should have been $expected, but was $code"
  exit 1
fi


# test userId is NOT in list

code=$(curl \
  --header "Content-Type: text/plain" \
  --user test:password \
  --request POST \
  --data '{"message":"{\"timeRangeStart\":1571245940546,\"timeRangeEnd\":1571246360547,\"userId\":\"BAD-USER-ID\",\"appId\":\"com.nike.ntc.brand.ios\",\"sources\":[\"nike.ntc.ios\"],\"metricTypes\":[\"rpe\",\"calories\",\"nikefuel\"],\"activityId\":\"8ed06ba3-d12c-4dc1-a773-cba81a0f0c5c\",\"receivedTime\":1571246402784,\"changeToken\":\"5819147260e25392eecbb1ab10480a1ed3bc600c8a379a88a035fa163d505e44:1571246402784\",\"changeType\":\"update\",\"payloadType\":\"activity\",\"session\":false,\"activityType\":\"training\"}","trace":{"parentId":"-2721724131837535344","spanId":"-8694889937887914020","spanName":"persistAndEnqueueSync","userId":"0353d6f5-f7e9-4830-a803-a1fc370bfa04","traceId":"0c967b6959f4284c","sampleable":false,"traceStartTimeNanos":1017120644185959}}' \
  -o /dev/null \
  -s \
  -w "%{http_code}" \
  localhost:3000/omg/wtf)

expected=204
if [ "$code" != "$expected" ]; then
  echo "Failed! Reponse code should have been $expected, but was $code"
  exit 1
fi

# # test missing auth
#
# code=$(curl \
#   --header "Content-Type: text/plain" \
#   --request POST \
#   --data '{"message":"{\"timeRangeStart\":1571245940546,\"timeRangeEnd\":1571246360547,\"userId\":\"6e3a7fe8-c4c9-41dd-8510-0c203b75e09a\",\"appId\":\"com.nike.ntc.brand.ios\",\"sources\":[\"nike.ntc.ios\"],\"metricTypes\":[\"rpe\",\"calories\",\"nikefuel\"],\"activityId\":\"8ed06ba3-d12c-4dc1-a773-cba81a0f0c5c\",\"receivedTime\":1571246402784,\"changeToken\":\"5819147260e25392eecbb1ab10480a1ed3bc600c8a379a88a035fa163d505e44:1571246402784\",\"changeType\":\"update\",\"payloadType\":\"activity\",\"session\":false,\"activityType\":\"training\"}","trace":{"parentId":"-2721724131837535344","spanId":"-8694889937887914020","spanName":"persistAndEnqueueSync","userId":"0353d6f5-f7e9-4830-a803-a1fc370bfa04","traceId":"0c967b6959f4284c","sampleable":false,"traceStartTimeNanos":1017120644185959}}' \
#   -o /dev/null \
#   -s \
#   -w "%{http_code}" \
#   localhost:3000/omg/wtf)
#
# expected=401
# if [ "$code" != "$expected" ]; then
#   echo "Failed! Reponse code should have been $expected, but was $code"
#   exit 1
# fi

sleep 3
